[project]
name = "python-containers"
version = "0"
requires-python = ">= 3.12"

[tool.pip-tools]
allow-unsafe = true
generate-hashes = true
reuse-hashes = true
strip-extras = true

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
