name: Build

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - run: echo $TMPDIR

      - run: ls -la /var/tmp/

      - name: Setup pip cache
        uses: actions/cache@v4
        with:
          path: /var/tmp/buildah-cache/root/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Podman build
        run: podman build .
