name: Build Images

#on:
#  pull_request:
#  push:
#    branches:
#      - main
#    paths-ignore:
#      - '*.md'
#  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "RUNNER_UID=$UID" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: /var/tmp/buildah-cache-${{ env.RUNNER_UID }}/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: podman build vdirsyncer
